runtime: php
env: flex

runtime_config:
  document_root: public


skip_files:
   .env

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:ZgDXwd82ynaMkFc6zS1P+AVkLsLnHdSwIdHgogOgm9A=
  APP_STORAGE: /tmp